//major=0
//minor=4
//build=2
//revision=1

//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;

[assembly: AssemblyVersion("0.4.2.1")]
